export const S = {
  page: { minHeight:'100vh', position:'relative', zIndex:1, fontFamily:"var(--font-b)" },
  inner: { maxWidth:640, margin:'0 auto', padding:'48px 24px' },
  progress: { display:'flex', gap:4, marginBottom:48 },
  bar: (a) => ({ flex:1, height:3, borderRadius:2, background: a ? 'var(--accent)' : 'rgba(255,255,255,0.06)', transition:'all 0.4s ease', boxShadow: a ? '0 0 8px var(--accent-glow)' : 'none' }),
  label: { fontSize:11, fontWeight:500, letterSpacing:'0.12em', textTransform:'uppercase', color:'var(--accent)', marginBottom:14, fontFamily:'var(--font-h)' },
  h2: { fontSize:24, fontWeight:500, letterSpacing:'-0.02em', color:'var(--text-primary)', marginBottom:12, lineHeight:1.35, fontFamily:'var(--font-h)' },
  sub: { fontSize:15, color:'var(--text-secondary)', marginBottom:28, lineHeight:1.7 },
  body: { fontSize:15, color:'var(--text-secondary)', lineHeight:1.7, marginBottom:24 },
  note: { fontSize:13, color:'var(--text-muted)', lineHeight:1.6, padding:'14px 18px', background:'var(--bg-card)', borderRadius:12, border:'1px solid var(--border)', marginTop:20 },
  opt: (sel) => ({
    display:'block', width:'100%', textAlign:'left', cursor:'pointer',
    background: sel ? 'var(--bg-elevated)' : 'var(--bg-card)',
    border: sel ? '1px solid var(--accent)' : '1px solid var(--border)',
    borderRadius:12, padding:'16px 18px', marginBottom:8,
    fontSize:14, color: sel ? 'var(--text-primary)' : 'var(--text-secondary)', lineHeight:1.6,
    fontWeight: sel ? 500 : 400, transition:'all 0.2s',
    boxShadow: sel ? '0 0 16px var(--accent-glow)' : 'none',
  }),
  multiOpt: (sel, max, count) => ({
    background: sel ? 'var(--bg-elevated)' : 'var(--bg-card)',
    border: sel ? '1px solid var(--accent)' : '1px solid var(--border)',
    borderRadius:10, padding:'12px 14px', textAlign:'left', cursor:'pointer',
    fontSize:13, fontWeight: sel ? 500 : 400,
    color: sel ? 'var(--text-primary)' : 'var(--text-secondary)',
    transition:'all 0.2s', opacity: !sel && count>=max ? 0.25 : 1,
    boxShadow: sel ? '0 0 12px var(--accent-glow)' : 'none',
  }),
  specRow: { marginBottom:32 },
  specPoles: { display:'flex', justifyContent:'space-between', marginTop:8 },
  specPole: { fontSize:12, color:'var(--text-muted)', maxWidth:'42%', lineHeight:1.5 },
  nav: { display:'flex', justifyContent:'space-between', marginTop:48, paddingBottom:48 },
  btnP: (ok) => ({
    background: ok ? 'var(--accent)' : 'rgba(255,255,255,0.04)',
    color: ok ? '#0B0D11' : 'var(--text-muted)',
    border:'none', padding:'14px 32px', borderRadius:10,
    cursor: ok ? 'pointer' : 'default',
    fontFamily:'var(--font-h)', fontSize:14, fontWeight:600,
    transition:'all 0.3s',
    boxShadow: ok ? '0 0 24px var(--accent-glow)' : 'none',
  }),
  btnS: { background:'transparent', border:'1px solid var(--border)', color:'var(--text-secondary)', padding:'12px 24px', borderRadius:10, cursor:'pointer', fontFamily:'var(--font-h)', fontSize:14, transition:'all 0.2s' },
  count: { fontSize:12, color:'var(--text-muted)', marginTop:10 },
  scene: { background:'var(--bg-card)', border:'1px solid var(--border)', borderRadius:12, padding:'16px 18px', marginBottom:20, fontSize:14, lineHeight:1.7, color:'var(--text-secondary)' },
  sceneLabel: { fontSize:11, fontWeight:600, color:'var(--accent-amber)', marginBottom:6, textTransform:'uppercase', letterSpacing:'0.06em', fontFamily:'var(--font-h)' },
  textarea: { width:'100%', minHeight:120, padding:'16px 18px', border:'1px solid var(--border)', borderRadius:12, fontSize:14, fontFamily:'var(--font-b)', lineHeight:1.7, color:'var(--text-primary)', background:'var(--bg-card)', resize:'vertical', outline:'none', transition:'all 0.2s' },
  input: { width:'100%', padding:'14px 16px', border:'1px solid var(--border)', borderRadius:10, fontSize:14, fontFamily:'var(--font-b)', color:'var(--text-primary)', background:'var(--bg-card)', outline:'none', transition:'all 0.2s' },
}
